# Generated by Django 4.1.7 on 2023-05-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_register_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='uid',
        ),
    ]
