# Generated by Django 4.1.7 on 2023-05-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_register_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
