# Generated by Django 4.1.7 on 2023-05-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_register_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
